### ISSUE TITLE
Make a new eval command to support other languages

### ISSUE THREAD

**Issue by rgoliveira** [rgoliveira/AwesomeBot#10]
It would work like the current `jseval`, but accept another languages. The best shot right now would be to integrate with an external service.

Services known at this time:
- [repl.it](https://repl.it/)
- others (I really didn't look much into this)

**Comment by kluge-iitk** [comment]
There's [ideone](https://ideone.com/) as well

There are also skulpt/brython for python

**Comment by raylu** [comment]
I use `nsjail` to run ruby/python3/node on my IRC bot: https://github.com/raylu/pbot/blob/e6574964b2d7c92f156e115f1b837e86fb00321d/commands.py#L216

**Comment by rgoliveira** [comment]
Sounds promising. Thank for the info, @raylu!

**Comment by moonheart08** [comment]
You could try using a usermodelinux sandbox by the name of umlbox, its known secure (there is a irc bot that has run for several years that uses it as a user sandbox), and works nicely.

**Comment by rgoliveira** [comment]
To avoid having to deal with complex installations and make deployment a burden, I'll try to integrate with repl.it. [Their plans](https://repl.it/site/api) include free a tier with 25k runs per month. You just have to sign in and get a token to consume the service.

**Comment by rgoliveira** [comment]
A new eval command was introduced in commit cd0b07561636f2786f4044908e4fb2c3977cff15. It uses repl.it integration and is already live.
