### ISSUE TITLE
Weather needs verbose flag

### ISSUE THREAD

**Issue by lethargilistic** [rgoliveira/AwesomeBot#36]
The weather command gives too much information by default. On mobile, it scrolls me an entire screen. I suggest adding a flag to it to get all of that data, if desired, but defaulting to just the summary, temperature, and humidity. Preferably one line. 

Remember, people use weather commands all the time.

**Comment by rgoliveira** [comment]
Maybe we could use less fields, like merge both temp units together, the same for the address and timezone, etc

**Comment by lethargilistic** [comment]
That's another solution, sure. I didn't want to demand less information, in case anyone was married to knowing the air pressure, timezone, and such,

**Comment by Samoxive** [comment]
What would be the command for verbosity, is !bot weather -v adress good enough?

**Comment by rgoliveira** [comment]
Maybe try to bundle similar info into the same field first. I think all those fields are requiring too much space.

If it turns out too big still, I guess a simple `-v` should suffice to enable all the info.

**Comment by Samoxive** [comment]
we can merge celcius and fahrenheit degrees into one field, other suggestions?

**Comment by rgoliveira** [comment]
OK, this is what we have today:

```
embed.setColor('#4286f4')
             .setFooter(`Local Time: ${dateString}`)
             .setTitle(`Weather in ${address}`)
             .addField('Summary', summary)
             .addField('Temperature °C', `${temperatureC} °C`, true)
             .addField('Temperature °F', `${temperatureF} °F`, true)
             .addField('Timezone', weatherData.timezone, true)
             .addField('Humidity', `${humidity}%`, true)
             .addField('Wind Speed', `${windSpeed} km/h`, true)
             .addField('Air Pressure', `${pressure} mbar`, true)
             .setDescription(weatherConfig.icons[weatherData.currently.icon]);
```

Here's my ideas:

- (-1) don't slice the timezone from `dateString` so it'll appear in the footer, and remove field "Timezone"
- (-1) put both temp units in the same field 
- (-1) remove air pressure (?)

**Comment by rgoliveira** [comment]
Maybe even merge humidity and wind speed

**Comment by melmsie** [comment]
+1 to all rg's ideas.

**Comment by Samoxive** [comment]
#49 fixed here
