### ISSUE TITLE
Add simple tests to avoid breaking changes

### ISSUE THREAD

**Issue by rgoliveira** [rgoliveira/AwesomeBot#40]
I guess after PR #34, which broke the bot, we could use a couple simple tests to avoid major problems. I'm proposing the following just for starters:

- [x] Make sure the bot can connect and disconnect to Discord

One thing I'm not sure about how to solve is where we should keep the APIs keys, but I think I can set them up in Travis. We'd just need to review the code and make sure it also looks for the keys in environment variables (the weather plugin is the only one requiring keys, IIRC).

**Comment by raylu** [comment]
Depending on external resources in your unit tests is not a great idea.

**Comment by rgoliveira** [comment]
It's infeasible to test a Discord bot without having a single connect/disconnect test. Also, there's no acceptable way to mock this connection.

We're building a bot to work with this service. We have to suppose it's working as expected and test our interactions with it. We should, on the other hand, do our best to isolate the code that don't actually need an active connection.

**Comment by raylu** [comment]
It is highly feasible to test some code who's primary purpose is integrating with an external service without an integration test.

The specific breakage in #34 could have been caught by attempting to run the misdeclared function. It involved no complex interaction with the Discord API. One way is to connect to something resembling the Discord API (I'm not convinced there's no way to mock Discord). Another is to just run the function and see if it even executes.

Here's an example of some client code (who's primary purpose is to talk to memcached) that doesn't rely on running a real memcached: https://github.com/mixpanel/memcache_client/blob/master/test.py
While memcached is simple to mock, being disconnected from a server is too.

**Comment by rgoliveira** [comment]
I think memcached is a poor example as it is trivial to mock. I'd be happy to use something like this for Discord if it'd simple to maintain.

I'd say it's OK for a test to fail if Discord is, for example, offline (and this is probably the worst case). You wouldn't be able to do anything anyway.

Right now I'm more concerned about running our code to check if it's working, not if an external service is working as it was yesterday. I totally understand where your concern is coming from, but this is not an easy thing to solve and should not hinder our progress writing tests. 

If somebody can come up with a reasonable way to mock the connection, it should be easy to adjust the tests accordingly.

**Comment by rgoliveira** [comment]
As a fuel for thought about the mocking: maybe it'd be possible to save some sample responses from the API and base the mock responses on those.

**Comment by rgoliveira** [comment]
Also, there's this question on discord.js: https://github.com/hydrabolt/discord.js/issues/727

**Comment by raylu** [comment]
You are trying to solve the problem of "our tests don't indicate if we integrate properly with the Discord API" but I'm saying we should solve the problem of "our tests don't indicate if `onDisconnect` and `onError` can't even be run". The latter is about the same difficulty as mocking memcached and has the obvious benefit of preventing the previous breakage.

The entire reason for unit testing is it's both easier to do and it provides the same benefits as integration testing, even in cases where you're primarily integrating against something else ([study](http://www.lexjansen.com/phuse/2010/rg/RG01.pdf)). If you don't believe that, then this entire unit testing fad is a waste of time and we shouldn't bother with it.

**Comment by rgoliveira** [comment]
@raylu I'm not saying we won't solve the problems you mentioned. Of course we will and those examples are the ones we can test even without an active connection (maybe just emitting fake events to the bot?).

My arguments were for the need to have, *for starters*, tests like the one I'm proposing: connecting and disconnecting. Just the initialization of the bot runs a lot of stuff, including loading all the plugins. This will ensure the bot can at least boot properly.

Some tests will be easier to write, like just invoking simple event handlers like `onDisconnect` and `onError`. Others will require to have an actual integration to the services we connect to, since most of the bot functions are reactions to messages it receives (and as of right now I have no idea how to test that).

So what I'm saying is: we should try to rely as little as possible on Discord, but (at least for now) a few tests will require the connection.

**Comment by rgoliveira** [comment]
I guess the point of this issue was addressed by PR #46.
