### ISSUE TITLE
jseval is escapeable

### ISSUE THREAD

**Issue by moonheart08** [rgoliveira/AwesomeBot#44]
Example:
!bot jseval console.log.constructor("return process")()

This will return the actual process object from outside the VM.
The only way to make a safe javascript sandbox is to compile your own, i recommend compiling a custom sandbox built off of the V8 engine.

**Comment by rgoliveira** [comment]
I guess this is related to #10, since we're looking for new ways to evaluate code

**Comment by rgoliveira** [comment]
Closing this, since jseval is gone (6a28752dd49deadf0d0fb2a7a8cea1d95cf324f5) and there's a new eval command using repl.it integration (cd0b07561636f2786f4044908e4fb2c3977cff15).

Again, thanks for the report!
