### ISSUE TITLE
Create something to keep track of channel status

### ISSUE THREAD

**Issue by rgoliveira** [rgoliveira/AwesomeBot#9]
New idea: passive thing to log channel status every <insert X units of time here>. Like:
- [ ] overall members online
- [ ] members per channel
- [ ] message count
- [ ] new users
- [ ] etc...

This way we could see the most active hours, channels, where we need more attention, this kinda thing

**Comment by moonheart08** [comment]
I think i could look into this.

**Comment by rgoliveira** [comment]
I think @Samoxive and/or @melmsie were a bit into this. Maybe check if they already did something.
If any of you are, please open a WIP pull request so we can see it's being worked on.

**Comment by superstabby** [comment]
Hacking something together for this right now. If someone else is doing it, that's fine. It is partly a learning exercise for me. :)

**Comment by rgoliveira** [comment]
For future reference: for now, this is being developed by @superstabby in his own bot (https://github.com/superstabby/StabbyStats). Maybe we'll merge these bots at some point.
